/* opAuth:{是否登录（登录用户1，非登录用户0），是否认证（已认证1，未认证0）} */
var operate_auth_json = {	privJson:[
	{
	  opId:'1',
	  opName:'zhan',
	  opDesc:'赞',
	  opAuth:[0,0]
	},{
	  opId:'2',
	  opName:'share',
	  opDesc:'分享',
	  opAuth:[1,0]
	},{
	  opId:'3',
	  opName:'collect',
	  opDesc:'收藏',
	  opAuth:[1,0]
	},{
	  opId:'4',
	  opName:'transmit',
	  opDesc:'转发',
	  opAuth:[1,0]
	},{
	  opId:'5',
	  opName:'note',
	  opDesc:'笔记',
	  opAuth:[1,0]
	},{
	  opId:'6',
	  opName:'respond',
	  opDesc:'回应',
	  opAuth:[1,1]
	},{
	  opId:'7',
	  opName:'publisArticle',
	  opDesc:'发布新文章',
	  opAuth:[1,1]
	},
	{
	  opId:'8',
	  opName:'follow',
	  opDesc:'关注',
	  opAuth:[1,1]
	},{
	  opId:'9',
	  opName:'viewResource',
	  opDesc:'资源查看（文库、文章、视频）',
	  opAuth:[1,1]
	},{
	  opId:'10',
	  opName:'accessBlogHome',
	  opDesc:'个人主页访问权限',
	  opAuth:[1,1]
	},{
	  opId:'11',
	  opName:'meetingVideo',
	  opDesc:'展视互动视频直播及点播',
	  opAuth:[1,1]
	},{
	  opId:'12',
	  opName:'meetingVideo2',
	  opDesc:'展视互动视频直播及点播',
	  opAuth:[1,0]
	},{
	  opId:'13',
	  opName:'meetingVideo3',
	  opDesc:'展视互动视频直播及点播',
	  opAuth:[0,0]
	},{
		opId:"14",
		opName:"onlyValidate",
		opDesc:"用于处理单纯登陆用户想认证",
		opAuth:[1,1]
	}]

};